name: dependabot
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: langston-barrett/gha/.github/workflows/merge-dependabot-prs.yml@b44a985fce946d41805fe58f746e46d04c612b43
    with:
      only-patch: false
