name: dependabot
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: langston-barrett/gha/.github/workflows/merge-dependabot-prs.yml@7c0b05df2a8448a462b987298e62bf8f61776fef
    with:
      only-patch: false
