name: dependabot
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: langston-barrett/gha/.github/workflows/merge-dependabot-prs.yml@9c2fa6aecfca059cb23255f6e4f84f8227801812
    with:
      only-patch: false
