name: lint
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - uses: langston-barrett/gha/.github/actions/install-linters@9c2fa6aecfca059cb23255f6e4f84f8227801812
    - uses: langston-barrett/lun/.github/actions/lun@4ff0bb8913126e9f4660c6fb2a10e868e709c9b7
      with:
        flags: "--color=always"
        run-flags: "--check --skip-tool='cargo clippy'"
