name: rust release
on:
  push:
    branches:
    - release*
    tags:
    - v*
  pull_request:
    paths: [".github/workflows/rust-release.yml"]
  workflow_dispatch:

jobs:
  release:
    uses: langston-barrett/gha/.github/workflows/rust-release.yml@9c2fa6aecfca059cb23255f6e4f84f8227801812
    with:
      publish: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
    permissions:
      contents: write